# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/renderer',
                'doc_host': 'https://flupppi.github.io',
                'git_url': 'https://github.com/flupppi/renderer',
                'lib_path': 'renderer'},
  'syms': {'renderer.core': {'renderer.core.foo': ('core.html#foo', 'renderer/core.py')}}}
